# Generated by Django 2.1.4 on 2019-01-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_co_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co_school',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='co_school',
            name='jurisdiction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='co_school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='co_school',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
