# Generated by Django 2.1.4 on 2019-01-04 01:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20190104_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_Bound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('aland', models.CharField(max_length=50)),
                ('awater', models.CharField(max_length=50)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
