# Generated by Django 2.1.4 on 2019-01-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_state_bound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state_bound',
            name='aland',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='state_bound',
            name='awater',
            field=models.IntegerField(max_length=50),
        ),
    ]
